# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e0ad1fc94556fb79699a5a956f64f15a3de81e53842252c12623f23c159469d65cceeba67fffa78cfd3893ac6b5796fd2ea960ab15ed6c9ae024fa70ae580e8

test:
  secret_key_base: e760a6fc96a10144a6c2384772acfd0f67ff59da18d835529617f95d97435c49aeebd1c9e0da08da4d5b002b2322dce98574e93503c10d03443e93775b1defd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
